name: research_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - python=3.12
  - numpy=1.26.4
  - pandas=2.1.4
  - scipy=1.11.4
  - pyarrow=14.0.2
  - pip:
      - world_bank_data==0.1.3
      - yaspin==3.0.1
      - simple_term_menu==1.6.4
      - rich==13.7.1